turing_garden = Garden.create!(name: 'Turing Community Garden', organic: true)
library_garden = Garden.create!(name: 'Public Library Garden', organic: true)
other_garden = Garden.create!(name: 'Main Street Garden', organic: false)

turing_garden.plots.create!(number: 25, size: "Large", direction: "East")
turing_garden.plots.create!(number: 26, size: "Small", direction: "West")
library_garden.plots.create!(number: 2, size: "Small", direction: "South")
other_garden.plots.create!(number: 738, size: "Medium", direction: "West")

garden = Garden.create!(name: "Jamie's Garden", organic: true)
plot1 = garden.plots.create!(number: 1, size: "Large", direction: "West")
plot2 = garden.plots.create!(number: 2, size: "Small", direction: "East")
plant1 = Plant.create!(name: "Golden Tomato", description: "Medium sun", days_to_harvest: 50)
plant2 = Plant.create!(name: "Special Lettuce", description: "Mostly shade, lots of water", days_to_harvest: 60)
plant3 = Plant.create!(name: "String Beans", description: "Medium sun, rich soil", days_to_harvest: 70)
plotplant1 = PlotPlant.create!(plant_id: plant1.id, plot_id: plot1.id)
plotplant1 = PlotPlant.create!(plant_id: plant2.id, plot_id: plot1.id)
plotplant1 = PlotPlant.create!(plant_id: plant3.id, plot_id: plot1.id)
plotplant1 = PlotPlant.create!(plant_id: plant3.id, plot_id: plot2.id)
